import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import * as fontkit from "fontkit";

/**
 * Brand outliner (`yarn brand`). Converts the brand text (the Б glyph, the
 * "Bukvar" wordmark, the OG tagline) into <path> geometry and writes the
 * outlined SVG sources that generate-icons.mjs rasterizes. Re-run it only when
 * the glyph, wordmark, or tagline actually changes.
 *
 * Outlining keeps generate-icons.mjs and the build font-free and
 * host-independent: librsvg/sharp render <path> without needing any font
 * installed. (A live `font-family` silently fell back to a generic serif on any
 * host lacking the font, notably Georgia, absent on Linux/CI.) The static
 * @fontsource weights it reads mirror the @fontsource-variable release the app
 * ships, so the outlined brand text uses the same typeface as the running app.
 */

const root = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const font = async (p) =>
  fontkit.create(await readFile(root(`node_modules/${p}`)));

// Bold (700) Source Serif 4 for the Cyrillic Б and the Latin wordmark; regular
// (400) Inter for the tagline. Static weights: fontkit can't instance the
// variable @fontsource-variable builds the app ships.
const ssCyr = await font(
  "@fontsource/source-serif-4/files/source-serif-4-cyrillic-700-normal.woff2",
);
const ssLat = await font(
  "@fontsource/source-serif-4/files/source-serif-4-latin-700-normal.woff2",
);
const inter = await font(
  "@fontsource/inter/files/inter-latin-400-normal.woff2",
);

const round = (n) => Number(n.toFixed(2));
const CMD = {
  moveTo: "M",
  lineTo: "L",
  quadraticCurveTo: "Q",
  bezierCurveTo: "C",
  closePath: "Z",
};

// Lay `text` out left-to-right with baseline at y=0, x origin at 0, scaled to
// `fontSize` and Y-flipped into SVG space. Returns the merged path `d`, the
// advance width, and the geometric bbox (for centering).
function outline(fnt, text, fontSize) {
  const scale = fontSize / fnt.unitsPerEm;
  const run = fnt.layout(text);
  const parts = [];
  let pen = 0;
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  run.glyphs.forEach((glyph, i) => {
    const pos = run.positions[i];
    const ox = pen + (pos.xOffset ?? 0);
    const oy = pos.yOffset ?? 0;
    for (const { command, args } of glyph.path.commands) {
      const coords = [];
      for (let k = 0; k < args.length; k += 2) {
        const x = (ox + args[k]) * scale;
        const y = -(oy + args[k + 1]) * scale;
        coords.push(round(x), round(y));
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
      parts.push(
        coords.length ? `${CMD[command]}${coords.join(" ")}` : CMD[command],
      );
    }
    pen += pos.xAdvance;
  });
  return {
    d: parts.join(""),
    width: round(run.advanceWidth * scale),
    cx: (minX + maxX) / 2,
    cy: (minY + maxY) / 2,
  };
}

const place = (o, tx, ty, fill) =>
  `<path transform="translate(${round(tx)} ${round(ty)})" d="${o.d}" fill="${fill}"/>`;

// Centre the glyph's bbox at (cx, cy).
const centred = (fnt, text, size, cx, cy, fill) => {
  const o = outline(fnt, text, size);
  return place(o, cx - o.cx, cy - o.cy, fill);
};
// Left edge at `left`, alphabetic baseline at `baseline`.
const leftAligned = (fnt, text, size, left, baseline, fill) =>
  place(outline(fnt, text, size), left, baseline, fill);

const note = (text) =>
  `<!-- Generated by scripts/outline-brand.mjs: do not edit by hand. Text outlined: ${text} -->`;

const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="Bukvar">
  ${note('"Б" (Source Serif 4 Bold)')}
  <rect width="512" height="512" rx="104" fill="#16213a"/>
  ${centred(ssCyr, "Б", 320, 256, 512 * 0.52, "#faf6ef")}
</svg>
`;

const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="Bukvar">
  ${note('"Б" (Source Serif 4 Bold)')}
  <rect width="64" height="64" rx="14" fill="#16213a"/>
  ${centred(ssCyr, "Б", 42, 32, 64 * 0.53, "#faf6ef")}
</svg>
`;

// Full-bleed (no rounded corners) for the maskable + Apple icons, which apply
// their own mask. The glyph sits inside the ~80% maskable safe zone.
const maskable = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  ${note('"Б" (Source Serif 4 Bold)')}
  <rect width="512" height="512" fill="#16213a"/>
  ${centred(ssCyr, "Б", 300, 256, 512 * 0.52, "#faf6ef")}
</svg>
`;

const og = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  ${note('"Б" / "Bukvar" (Source Serif 4 Bold) + "Learn Serbian Cyrillic — free & open" (Inter)')}
  <rect width="1200" height="630" fill="#16213a"/>
  <rect x="96" y="175" width="280" height="280" rx="56" fill="#faf6ef"/>
  ${centred(ssCyr, "Б", 200, 236, 315, "#16213a")}
  ${leftAligned(ssLat, "Bukvar", 104, 432, 300, "#faf6ef")}
  ${leftAligned(inter, "Learn Serbian Cyrillic — free & open", 40, 436, 384, "#f3ece0")}
</svg>
`;

await writeFile(root("public/icon.svg"), icon);
await writeFile(root("public/favicon.svg"), favicon);
await mkdir(root("scripts/brand"), { recursive: true });
await writeFile(root("scripts/brand/maskable.svg"), maskable);
await writeFile(root("scripts/brand/og.svg"), og);
console.log(
  "wrote outlined SVGs: public/icon.svg, public/favicon.svg, scripts/brand/{maskable,og}.svg",
);
